name: Build and merge containers

on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

env:
  IS_APPROVED: ${{ github.event.review.state == 'approved' && github.event.pull_request.draft == false }}

permissions:
  packages: write
  contents: write
  id-token: write
  attestations: write

jobs:

  build_container:
    if: ${{ env.IS_APPROVED }}
    name: Build and Push Containers
    strategy:
      fail-fast: false
      matrix:
        model: [flair, roberta, roberta_german, gliner]
        os: [blacksmith-2vcpu-ubuntu-2404, blacksmith-2vcpu-ubuntu-2404-arm]
    uses: taranis-ai/github-actions/.github/workflows/build-multiarch-bot-container.yml@master
    with:
      ghcr_image: ghcr.io/taranis-ai/taranis-nlp-bot
      model: ${{ matrix.model }}
      os: ${{ matrix.os }}

  merge_container:
    if: ${{ env.IS_APPROVED }}
    name: Merge Container Manifests
    needs: build_container
    strategy:
      fail-fast: false
      matrix:
        model: [flair, roberta, roberta_german, gliner]
    uses: taranis-ai/github-actions/.github/workflows/merge-multiarch-bot-container.yml@master
    with:
      ghcr_image: ghcr.io/taranis-ai/taranis-nlp-bot
      model: ${{ matrix.model }}
      latest: ${{ matrix.model == 'flair' }}
