name: Smoke test
on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]
  push:

jobs:
  test_docker_deployment:
    if: ${{ github.event.review.state == 'approved' || github.event_name == 'workflow_dispatch' || true }}
    runs-on: ubuntu-latest

    steps:
      - name: Run smoke test
        uses: taranis-ai/github-actions/.github/workflows/smoke-test.yml@smoke-test
        with:
          TAG: ${{ github.ref_name }}
          REPO_NAME: ${{ github.event.repository.name }}
