name: Smoke test
permissions:
  contents: read
on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]
  push:

jobs:
  test_docker_deployment:
    if: ${{ github.event.review.state == 'approved' || github.event_name == 'workflow_dispatch' || true}}
    uses: taranis-ai/github-actions/.github/workflows/smoke-test.yml@smoke-test
    with:
      repo_name: ${{ github.event.repository.name }}
