name: Smoke test
on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]
  push:

jobs:
  test_docker_deployment:
    if: ${{ github.event.review.state == 'approved' || github.event_name == 'workflow_dispatch' || true }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker images from PR code
        env:
            GITHUB_REPOSITORY_OWNER: ghcr.io/taranis-ai
        run: |
          chmod +x build_container.sh
          ./build_container.sh

      - name: Create a compose file on the fly
        run: |
          cat <<'EOF' > compose.e2e.yml
          services:
            nlp_bot:
              image: "${DOCKER_IMAGE_NAMESPACE}/taranis-nlp-bot:${TARANIS_BOT_TAG:-latest}"
              healthcheck:
                test: ["CMD-SHELL", "python -c \"import requests; requests.get('http://localhost:8000/health', timeout=5).raise_for_status()\""]
                interval: 1m30s
                timeout: 30s
                retries: 5
                start_period: 30s
              environment:
                API_KEY: "${BOT_API_KEY}"
                DEBUG: "${DEBUG:-False}"
          EOF

      - name: Run docker compose for last commit
        env:
          BOT_API_KEY: testkey
          DOCKER_IMAGE_NAMESPACE: ghcr.io/taranis-ai
          TARANIS_BOT_TAG: latest
        run: |
          docker compose -f compose.e2e.yml up --pull=never --wait-timeout=60 --wait
          echo "Echo docker ps -a:"
          docker ps -a
          echo "Echo core logs:"
          docker compose logs core
          docker compose down
