name: Smoke test
on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]
  push:

jobs:
  test_docker_deployment:
    if: ${{ github.event.review.state == 'approved' || github.event_name == 'workflow_dispatch' || true }}
    runs-on: ubuntu-latest
    env:
      TARANIS_BOT_TAG: ${{ github.ref_name }}
      REPO_NAME: ${{ github.event.repository.name }}

    steps:
      - name: Build, no push
        uses: docker/build-push-action@v6
        with:
          file: Containerfile
          push: false
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run docker compose for last commit
        working-directory: docker/
        run: |
          docker compose -f compose.e2e.yml up --pull=never --wait-timeout=60 --wait
          echo "Echo docker ps -a:"
          docker ps -a
          echo "Echo logs:"
          docker compose logs
          docker compose down
